/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mnistandroid_pafprocess */

#ifndef _Included_com_example_mnistandroid_pafprocess
#define _Included_com_example_mnistandroid_pafprocess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_mnistandroid_pafprocess
 * Method:    process_paf
 * Signature: (III[FIII[FIII[F)I
 */
JNIEXPORT jint JNICALL Java_com_example_mnistandroid_pafprocess_process_1paf
  (JNIEnv *, jobject, jint, jint, jint, jfloatArray, jint, jint, jint, jfloatArray, jint, jint, jint, jfloatArray);

/*
 * Class:     com_example_mnistandroid_pafprocess
 * Method:    get_num_humans
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_mnistandroid_pafprocess_get_1num_1humans
  (JNIEnv *, jobject);

/*
 * Class:     com_example_mnistandroid_pafprocess
 * Method:    get_part_cid
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_mnistandroid_pafprocess_get_1part_1cid
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_mnistandroid_pafprocess
 * Method:    get_score
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_com_example_mnistandroid_pafprocess_get_1score
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_mnistandroid_pafprocess
 * Method:    get_part_x
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_mnistandroid_pafprocess_get_1part_1x
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_mnistandroid_pafprocess
 * Method:    get_part_y
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_mnistandroid_pafprocess_get_1part_1y
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_mnistandroid_pafprocess
 * Method:    get_part_score
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_com_example_mnistandroid_pafprocess_get_1part_1score
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
