/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_mnistandroid_pafprocess */
#include <vector>
#ifndef _Included_com_example_mnistandroid_pafprocess
#define _Included_com_example_mnistandroid_pafprocess
#ifdef __cplusplus
extern "C" {
#endif
//jfloatArray THRESH_HEAT;
const float THRESH_HEAT = 0.05;
//#define THRESH_HEAT 0.05;
const float THRESH_VECTOR_SCORE = 0.05;
const int THRESH_VECTOR_CNT1 = 6;
const int THRESH_PART_CNT = 4;
const float THRESH_HUMAN_SCORE = 0.3;
const int NUM_PART = 18;

const int STEP_PAF = 10;

const int COCOPAIRS_SIZE = 19;
const int COCOPAIRS_NET[COCOPAIRS_SIZE][2] = {
        {12, 13}, {20, 21}, {14, 15}, {16, 17}, {22, 23}, {24, 25}, {0, 1}, {2, 3}, {4, 5},
        {6, 7}, {8, 9}, {10, 11}, {28, 29}, {30, 31}, {34, 35}, {32, 33}, {36, 37}, {18, 19}, {26, 27}
};

const int COCOPAIRS[COCOPAIRS_SIZE][2] = {
        {1, 2}, {1, 5}, {2, 3}, {3, 4}, {5, 6}, {6, 7}, {1, 8}, {8, 9}, {9, 10}, {1, 11},
        {11, 12}, {12, 13}, {1, 0}, {0, 14}, {14, 16}, {0, 15}, {15, 17}, {2, 16}, {5, 17}
};

struct Peak {
    int x;
    int y;
    float score;
    int id;
};

struct VectorXY {
    float x;
    float y;
};

struct ConnectionCandidate {
    int idx1;
    int idx2;
    float score;
    float etc;
};

struct Connection {
    int cid1;
    int cid2;
    float score;
    int peak_id1;
    int peak_id2;
};
/*
 * Class:     com_example_mnistandroid_pafprocess
 * Method:    process_paf
 * Signature: (IIIFIIIFIIIF)I
 */

JNIEXPORT jint JNICALL Java_com_example_mnistandroid_pafprocess_process_1paf
        (JNIEnv *, jobject, jint, jint, jint, jfloatArray, jint, jint, jint, jfloatArray, jint, jint, jint, jfloatArray);
/*
 * Class:     com_example_mnistandroid_pafprocess
 * Method:    get_num_humans
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_mnistandroid_pafprocess_get_1num_1humans
  (JNIEnv *, jobject);

/*
 * Class:     com_example_mnistandroid_pafprocess
 * Method:    get_part_cid
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_example_mnistandroid_pafprocess_get_1part_1cid
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_example_mnistandroid_pafprocess
 * Method:    get_score
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_com_example_mnistandroid_pafprocess_get_1score
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_mnistandroid_pafprocess
 * Method:    get_part_x
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_mnistandroid_pafprocess_get_1part_1x
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_mnistandroid_pafprocess
 * Method:    get_part_y
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_mnistandroid_pafprocess_get_1part_1y
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_example_mnistandroid_pafprocess
 * Method:    get_part_score
 * Signature: (I)F
 */
JNIEXPORT jfloat JNICALL Java_com_example_mnistandroid_pafprocess_get_1part_1score
  (JNIEnv *, jobject, jint);





#ifdef __cplusplus
}
#endif
#endif
